spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 2314
mybatis-plus:
  type-aliases-package: com.example.classproject.eneity
  mapper-locations: classpath:/Mapper/*.xml
server:
  port: 9001
